version: '3.1'

services:

  mongo:
    image: mongo:4.1
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: yourpassword
    ports:
      - 27017:27017

networks:
  default:
    external:
      name: bysj_network