# Generated by Django 2.2.1 on 2019-06-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='采集站点名称')),
                ('spider_name', models.CharField(max_length=100, verbose_name='采集站点名称')),
                ('redis_key', models.CharField(max_length=100, verbose_name='采集站点名称')),
                ('start_urls', models.CharField(max_length=100, verbose_name='采集站点名称')),
                ('seconds', models.CharField(max_length=100, verbose_name='采集站点名称')),
                ('datetime', models.CharField(max_length=100, verbose_name='采集站点名称')),
                ('start_api', models.CharField(max_length=100, verbose_name='采集站点名称')),
            ],
            options={
                'verbose_name': '采集站点列表',
                'verbose_name_plural': '采集站点列表',
            },
        ),
    ]
