# Generated by Django 2.2.1 on 2019-06-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawllist',
            name='start_urls',
        ),
        migrations.AlterField(
            model_name='crawllist',
            name='datetime',
            field=models.CharField(max_length=100, verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='crawllist',
            name='redis_key',
            field=models.CharField(max_length=50, verbose_name='Redis Key值'),
        ),
        migrations.AlterField(
            model_name='crawllist',
            name='seconds',
            field=models.CharField(max_length=100, verbose_name='状态间隔'),
        ),
        migrations.AlterField(
            model_name='crawllist',
            name='site_name',
            field=models.CharField(max_length=100, verbose_name='站点名称'),
        ),
        migrations.AlterField(
            model_name='crawllist',
            name='spider_name',
            field=models.CharField(max_length=100, verbose_name='爬虫名称'),
        ),
        migrations.AlterField(
            model_name='crawllist',
            name='start_api',
            field=models.CharField(max_length=100, verbose_name='采集入口'),
        ),
    ]
