# Generated by Django 2.2.1 on 2019-06-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0003_auto_20190604_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawllist',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='crawllist',
            name='redis_key',
            field=models.CharField(max_length=20, verbose_name='Redis Key'),
        ),
    ]
