# Generated by Django 2.2.1 on 2019-06-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasummary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='contract',
            new_name='remark',
        ),
        migrations.AddField(
            model_name='datasummary',
            name='remark',
            field=models.TextField(blank=True, verbose_name='部门备注'),
        ),
        migrations.AddField(
            model_name='department',
            name='remark',
            field=models.TextField(blank=True, verbose_name='部门备注'),
        ),
        migrations.AddField(
            model_name='publicnotice',
            name='remark',
            field=models.TextField(blank=True, verbose_name='部门备注'),
        ),
        migrations.AddField(
            model_name='reportevent',
            name='remark',
            field=models.TextField(blank=True, verbose_name='部门备注'),
        ),
        migrations.AlterField(
            model_name='department',
            name='contract',
            field=models.CharField(max_length=100, verbose_name='联系方式'),
        ),
    ]
