# Generated by Django 2.2.1 on 2019-06-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasummary', '0002_auto_20190603_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicnotice',
            name='address',
        ),
        migrations.AddField(
            model_name='publicnotice',
            name='notices',
            field=models.ManyToManyField(blank=True, related_name='notice', to='datasummary.Department', verbose_name='通知部门'),
        ),
        migrations.AlterField(
            model_name='publicnotice',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='dealwiths', to='datasummary.Department', verbose_name='处理部门'),
        ),
    ]
