# Generated by Django 2.2.1 on 2019-06-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasummary', '0003_auto_20190603_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicnotice',
            name='contract',
        ),
        migrations.AlterField(
            model_name='datasummary',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='部门备注'),
        ),
        migrations.AlterField(
            model_name='department',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='部门备注'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='组织备注'),
        ),
        migrations.AlterField(
            model_name='publicnotice',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='部门备注'),
        ),
        migrations.AlterField(
            model_name='reportevent',
            name='contract',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='reportevent',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='部门备注'),
        ),
    ]
