# Generated by Django 2.2.1 on 2019-06-03 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasummary', '0004_auto_20190603_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasummary',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='department',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='组织备注'),
        ),
        migrations.AlterField(
            model_name='publicnotice',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='reportevent',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='reportevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportevents', to=settings.AUTH_USER_MODEL, verbose_name='处理人员'),
        ),
    ]
