# Generated by Django 2.2.1 on 2019-06-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasummary', '0005_auto_20190603_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasummary',
            options={'verbose_name': '舆情汇总', 'verbose_name_plural': '舆情汇总'},
        ),
        migrations.AlterField(
            model_name='datasummary',
            name='content_from',
            field=models.CharField(max_length=20, verbose_name='舆情来源'),
        ),
        migrations.AlterField(
            model_name='datasummary',
            name='content_url',
            field=models.CharField(max_length=200, verbose_name='舆情链接'),
        ),
        migrations.AlterField(
            model_name='datasummary',
            name='intro',
            field=models.CharField(max_length=200, verbose_name='舆情摘要'),
        ),
        migrations.AlterField(
            model_name='datasummary',
            name='title',
            field=models.CharField(max_length=100, verbose_name='舆情名称'),
        ),
        migrations.AlterField(
            model_name='publicnotice',
            name='deal_with_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
        migrations.AlterField(
            model_name='publicnotice',
            name='intro',
            field=models.CharField(max_length=200, verbose_name='舆情摘要'),
        ),
        migrations.AlterField(
            model_name='publicnotice',
            name='title',
            field=models.CharField(max_length=100, verbose_name='舆情名称'),
        ),
        migrations.AlterField(
            model_name='reportevent',
            name='content',
            field=models.TextField(verbose_name='舆情内容'),
        ),
        migrations.AlterField(
            model_name='reportevent',
            name='title',
            field=models.CharField(max_length=100, verbose_name='舆情名称'),
        ),
    ]
