# Generated by Django 2.2.1 on 2019-06-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasummary', '0006_auto_20190603_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasummary',
            name='lyric_attribute',
            field=models.CharField(choices=[('1', '正面'), ('0', '中立'), ('-1', '反面')], max_length=1, verbose_name='舆情属性'),
        ),
        migrations.AlterField(
            model_name='reportevent',
            name='address',
            field=models.CharField(max_length=100, verbose_name='舆情地点'),
        ),
    ]
