# Generated by Django 2.2.1 on 2019-06-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasummary', '0007_auto_20190603_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasummary',
            name='lyric_attribute',
            field=models.CharField(choices=[('1', '正面'), ('0', '中立'), ('-1', '反面')], max_length=2, verbose_name='舆情属性'),
        ),
    ]
