# Generated by Django 2.2.1 on 2019-06-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasummary', '0008_auto_20190603_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevent',
            name='lyric_attribute',
            field=models.CharField(blank=True, choices=[('1', '正面'), ('0', '中立'), ('-1', '反面')], max_length=2, null=True, verbose_name='舆情属性'),
        ),
        migrations.AlterField(
            model_name='datasummary',
            name='lyric_attribute',
            field=models.CharField(blank=True, choices=[('1', '正面'), ('0', '中立'), ('-1', '反面')], max_length=2, null=True, verbose_name='舆情属性'),
        ),
    ]
