# Generated by Django 2.2.1 on 2019-06-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasummary', '0009_auto_20190603_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevent',
            name='score',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='舆情评分'),
        ),
    ]
