# Generated by Django 2.2.1 on 2019-06-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasummary', '0010_reportevent_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportevent',
            name='score',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='舆情评分'),
        ),
    ]
