# Generated by Django 2.2.1 on 2019-06-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasummary', '0012_emailrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevent',
            name='keysword',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='关键词'),
        ),
    ]
