# Generated by Django 2.2.1 on 2019-06-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasummary', '0013_reportevent_keysword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportevent',
            old_name='keysword',
            new_name='keywords',
        ),
    ]
