# Generated by Django 2.2.1 on 2019-06-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasummary', '0014_auto_20190604_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportevent',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='关键词'),
        ),
    ]
