# Generated by Django 2.2.1 on 2019-06-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasummary', '0015_auto_20190604_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='舆情名称')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='评论内容')),
                ('commentary', models.TextField(blank=True, max_length=200, null=True, verbose_name='评论观点')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
            ],
        ),
    ]
