# Generated by Django 2.2.1 on 2019-06-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasummary', '0016_commentcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentcontent',
            options={'verbose_name': '内容评论', 'verbose_name_plural': '内容评论'},
        ),
        migrations.AddField(
            model_name='datasummary',
            name='summary',
            field=models.ManyToManyField(blank=True, null=True, related_name='summary', to='datasummary.Department', verbose_name='通知部门'),
        ),
    ]
